resources:
- repo: self
pool:
  vmImage: 'windows-2019'
steps:
- task: MSBuild@1
  displayName: Build
  inputs:
    solution: 'Soneta.Platform.Developer/Soneta.Platform.Developer.sln'
    configuration: 'Release'
    msbuildArguments: '/r'
- task: CopyFiles@2
  inputs:
    contents: '$(Agent.BuildDirectory)/bin/Release/*.nupkg'
    targetFolder: '$(Build.ArtifactStagingDirectory)'
    cleanTargetFolder: true
    flattenFolders: true
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
