resources:
- repo: self
pool:
  vmImage: 'windows-2019'
steps:
- task: MSBuild@1
  displayName: Build
  inputs:
    solution: '**/*.csproj'
    configuration: 'Release'
    msbuildArguments: '/r'
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    PathtoPublish: '$(build.artifactstagingdirectory)'
