resources:
- repo: self
pool:
  vmImage: 'ubuntu-latest'
variables:
  configuration: Release
  name: Soneta.Platform.Developer
steps:
- task: UseDotNet@2
  displayName: Install dotnet SDK
  inputs:
    packageType: sdk
    version: 8.0.404
- task: DotNetCoreCLI@2
  displayName: Build Solution Linux
  inputs:
    command: build
    projects: $(name)/$(name).sln
    arguments: 
      -c $(configuration)
- task: CopyFiles@2
  inputs:
    contents: $(name)/$(name)/bin/$(configuration)/**/?(*.nupkg)
    targetFolder: $(Build.ArtifactStagingDirectory)
    cleanTargetFolder: true
    flattenFolders: true
- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifact'
  inputs:
    artifactName: $(name)
    PathtoPublish: $(build.artifactstagingdirectory)
